version: '2'
volumes:
  esdata2:
  kibana-plugins:
  minio-data:

services:
  face:
    image: face
    build: .
    env_file:
      - s3.env
    # --reload is usefull for dev purposes.
    command: ["gunicorn","--reload","-c","gunicorn.py","app_falcon:app"]
    environment:
     - SERVER_PORT:5000
    volumes:
    #Mount the source in the folder is useful for dev purposes.
     - ./src:/usr/src/code
     - ./known/base.jpg:/usr/src/code/base.jpg:ro
     - ./unknown:/usr/src/code/unknown:ro
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: "tcp://192.168.122.1:24224"
        fluentd-async-connect: "true"
        # As stated in https://docs.docker.com/config/containers/logging/log_tags/
        tag: "frecognition.{{.ImageName}}/{{.Name}}/{{.ID}}"

  fluentd:
    image: fluentd:es
    build: ./fluentd
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
     - cluster.name=docker-cluster
     - bootstrap.memory_lock=true
     - ES_JAVA_OPTS=-Xms512m -Xmx512m
     - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata2:/usr/share/elasticsearch/data

  kibana:
    image: kibana:presentation
    build: kibana/
    restart: always
    networks:
     - default
    ports:
     - 5601:5601
    volumes:
     - kibana-plugins:/usr/share/kibana/plugins

  minio:
    image: minio/minio
    volumes:
      - minio-data:/export
    env_file:
      - s3.env
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: OTI14W1KOLISJCO3K61W
      MINIO_SECRET_KEY: rSNqAavaAEHdOcZwjWNcStd8HJwIXh5KFBnW8Bcz
    command: server /export
